project:
  type: website
  render:
    - "*.qmd"
    - "!post-with-code/"
    - "!welcome/"
    - "!2023-1-18-Observable JS in Quarto.qmd"  

website:
  title: "Quartotest"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: darkly
    css: styles.css



