project:
  type: website
  render:
    - "*.qmd"
    - "!post-with-code/"
    - "!welcome/"
    - "!2023-1-18-Observable JS in Quarto.qmd"  
    - "!2023-1-17-Jekyll on Windows and Mac.qmd"
    - "!playground/"
website:
  title: "Jeffrey Fonseca's old blog"
  navbar:
    left:
      - text: "NEW BLOG HERE"
        href: https://moonpiedumplings.github.io/
    right:
      - icon: github
        href: https://github.com/moonpiedumplings
format:
  html:
    theme: darkly
    css: styles.css



