---
title: "Compiling KasmVNC on NixOS"
date: "2023-5-2"
categories: [linux, devops, nix, kasm]
execute:
  freeze: auto
---

This is a living document, for the time being. Rather than a complete blogpost, this is a tracker of my progress, as well as a quick reference I can come back to.

# What is this?

Kasmweb is a software to create remote desktops, that exist within docker containers, and allow users to access them, all from a browser based GUI. 

Kasmvnc is the VNC server part of kasm web, a custom fork of previous existing features, enhanced with more performance, and most importantly, a web native setup. Incompatible with existing VNC protocols, the only way to access Kasmvnc is through the http/https serive it offers, the web based VNC ui. 

KasmVNC is an amazing piece of software, but development for it is not truly, fully public. This is present in their build system. Their build system is a series of bash scripts, that call docker containers, which call more bash scripts, to finally compile the software, and package it, all in one. 

As part of the scripts they have to compile kasm, lots of static linking happens. They do this because not all distros package the most updated, performant versions of the libraries that kasmvnc uses. 

But Nixos, the distro I want to package KasmVNC for, does. In addition to that, it is completely incompatible with the hacked together build system that kasm uses. In order to package KasmVNC for Nixos, I must reverse engineer their build system, and bit by bit, port it to NixOS. 

# Nixos Build System

How the nixos build system works. I will do later, but here I will document, step by step, how nixos builds a package.

# KasmVNC's Build System

Reverse engineering KasmVNC's build system. 


The below is what I neeed for the compiliation commands to work. I don't know where Kasm runs these commands, or similar equivalents, this is just what I've figured out. 

Perhaps I need to only run `make` in the KasmVNC/unix directory?

```{bash}

git clone https://github.com/TigerVNC/tigervnc

cd tigervnc

git clone https://github.com/kasmtech/KasmVNC

cd KasmVNC

cp ..vncserver .vncserver # this sets up build environment. I will still need to check if every single one of these things are necessary, but this works for now
```

The build script can be found [here](https://github.com/kasmtech/KasmVNC/blob/4d3a9b749adfcf89bde0b970c1c37481c92d585b/builder/build.sh#L63)

But from this build script, I don't think all of it is necessary. Below, I will extract what commands are actually needed, from all the fluff, cruft, and hacks. 

```{bash}

cmake -D CMAKE_BUILD_TYPE=RelWithDebInfo . -DBUILD_VIEWER:BOOL=OFF \
  -DENABLE_GNUTLS:BOOL=OFF

make
```

Builds end up in `KasmVNC/unix/`

Except the preliminary builds don't work. They error:

```{bash}

~/vscode/tigervnc/KasmVNC/unix master ?1 ❯ ./vncserver 

Can't locate List/MoreUtils.pm in @INC (you may need to install the List::MoreUtils module) (@INC contains: /usr/lib/perl5/5.36/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/5.36/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/5.36/core_perl /usr/share/perl5/core_perl) at ./vncserver line 38.
BEGIN failed--compilation aborted at ./vncserver line 38.

```

The above is probably because a perl library is missing. After attempting to install the missing library using `pacman -S perl-list-moreutils` I get a different error.

```{bash}

~/vscode/tigervnc/KasmVNC/unix master ?1 ❯ ./vncserver 

Can't locate KasmVNC/CliOption.pm in @INC (you may need to install the KasmVNC::CliOption module) (@INC contains: /usr/lib/perl5/5.36/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/5.36/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/5.36/core_perl /usr/share/perl5/core_perl) at ./vncserver line 42.
BEGIN failed--compilation aborted at ./vncserver line 42.

```

Obviously, this won't work. I must figure out why KasmVNC pacakges perl packages, where it puts them by default, and how to package them for Nix. 

Alright, the vncserver command appears to be in the git repo, and rather than being a binary, it is a wrapper script to start an xvnc server. from the script:

```
use KasmVNC::CliOption;
use KasmVNC::ConfigKey;
use KasmVNC::PatternValidator;
use KasmVNC::EnumValidator;
use KasmVNC::Config;
use KasmVNC::Users;
use KasmVNC::TextOption;
use KasmVNC::TextUI;
use KasmVNC::Utils;
use KasmVNC::Logger;

```

These perl modules/libraries can be found in `KasmVNC/unix/KasmVNC`

So that is what is necessary for the vncserver script to run. But is this script really necessary? Based on the names of the perl libraries, this script might not be adding any core functionalities to kasmvnc, only things like additional command line options, or loggers. 

I need to find where this script runs kasmvnc, and also where the actual kasmvnc binary is. 

I think their fork of xvnc is located in `KasmVNC/unix/xserver/hw/vnc/xvnc.c`.  

But I get compilation errors:

```

[nix-shell:~/vscode/tigervnc/KasmVNC]$ make 
[  3%] Built target os
[ 13%] Built target rdr
[ 30%] Built target network
[ 31%] Built target Xregion
[ 78%] Built target rfb
[ 80%] Built target tx
[ 81%] Built target unixcommon
[ 81%] Linking CXX executable vncconfig
/nix/store/178vvank67pg2ckr5ic5gmdkm3ri72f3-binutils-2.39/bin/ld: cannot find -lturbojpeg: No such file or directory
collect2: error: ld returned 1 exit status
make[2]: *** [unix/vncconfig/CMakeFiles/vncconfig.dir/build.make:157: unix/vncconfig/vncconfig] Error 1
make[1]: *** [CMakeFiles/Makefile2:610: unix/vncconfig/CMakeFiles/vncconfig.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

```

I don't know why this happens. For those who don't know, make pretty much calls a set of scripts, called Makefiles. I will need to find where in these scripts, the error commands are run. 

Weirdly, I can't reproduce outside of the build script:

```{bash}

~/vscode/tigervnc/KasmVNC master ?1 ❯ ld -lsdsakdfj
ld: cannot find -lsdsakdfj: No such file or directory
~/vscode/tigervnc/KasmVNC master ?1 ❯ ld -lturbojpeg
ld: warning: cannot find entry symbol _start; not setting start address
~/vscode/tigervnc/KasmVNC master ?2 ❯ ld -ljpeg     
ld: warning: cannot find entry symbol _start; not setting start address
~/vscode/tigervnc/KasmVNC master ?2 ❯ ld -ljpeg-turbo
ld: cannot find -ljpeg-turbo: No such file or directory
~/vscode/tigervnc/KasmVNC master ?1 ❯ 

```

I suspect the make scripts have some hacks that change working directory, or otherwise hide my installation of libjpeg. 
